/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './sections/**/*.liquid',
    './layout/**/*.liquid',
    './snippets/**/*.liquid',
    './templates/**/*.liquid',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#202D36',
        'secondary': '#929CAA',
        'accent-deep-red': '#3C0007',
        'accent-bright-red': '#6C0102',
      },
      fontFamily: {
        heading: ['Assistant', 'sans-serif'],
        body: ['Assistant', 'sans-serif'],
      },
      fontWeight: {
        'heading-weight': 'var(--font-heading-weight)',
        'body-weight': 'var(--font-body-weight)',
        'body-weight-bold': 'var(--font-body-weight-bold)',
      },
      fontSize: {
        'h0-mobile': '4rem',
        'h0-desktop': '5.2rem',
        'h1-mobile': '3rem',
        'h1-desktop': '4rem',
        'h2-mobile': '2rem',
        'h2-desktop': '2.4rem',
        'h3-mobile': '1.7rem',
        'h3-desktop': '1.8rem',
        'h4-mobile': '1.5rem',
        'h5-mobile': '1.2rem',
        'h5-desktop': '1.3rem',
        'body-mobile': '1.5rem',
        'body-desktop': '1.6rem',
      },
      spacing: {
        'sections-desktop': 'var(--spacing-sections-desktop)',
        'sections-mobile': 'var(--spacing-sections-mobile)',
        'grid-desktop-horizontal': 'var(--grid-desktop-horizontal-spacing)',
        'grid-desktop-vertical': 'var(--grid-desktop-vertical-spacing)',
        'grid-mobile-horizontal': 'var(--grid-mobile-horizontal-spacing)',
        'grid-mobile-vertical': 'var(--grid-mobile-vertical-spacing)',
      },
      borderRadius: {
        'buttons': 'var(--buttons-radius)',
        'inputs': 'var(--inputs-radius)',
        'variant-pills': 'var(--variant-pills-radius)',
        'text-boxes': 'var(--text-boxes-radius)',
        'media': 'var(--media-radius)',
        'cards': 'var(--cards-radius)',
        'popup': 'var(--popup-radius)',
        'drawer': 'var(--drawer-radius)',
        'badge': 'var(--badge-radius)',
      },
      borderWidth: {
        'buttons': 'var(--buttons-border)',
        'inputs': 'var(--inputs-border)',
        'variant-pills': 'var(--variant-pills-border)',
        'text-boxes': 'var(--text-boxes-border)',
        'media': 'var(--media-border)',
        'cards': 'var(--cards-border)',
        'popup': 'var(--popup-border)',
        'drawer': 'var(--drawer-border)',
        'badge': 'var(--badge-border)',
      },
      boxShadow: {
        'buttons': 'var(--buttons-shadow-offset) rgba(var(--color-shadow), var(--buttons-shadow-opacity))',
        'inputs': 'var(--inputs-shadow-offset) rgba(var(--color-shadow), var(--inputs-shadow-opacity))',
        'variant-pills': 'var(--variant-pills-shadow-offset) rgba(var(--color-shadow), var(--variant-pills-shadow-opacity))',
        'text-boxes': 'var(--text-boxes-shadow-offset) rgba(var(--color-shadow), var(--text-boxes-shadow-opacity))',
        'media': 'var(--media-shadow-offset) rgba(var(--color-shadow), var(--media-shadow-opacity))',
        'cards': 'var(--cards-shadow-offset) rgba(var(--color-shadow), var(--cards-shadow-opacity))',
        'popup': 'var(--popup-shadow-offset) rgba(var(--color-shadow), var(--popup-shadow-opacity))',
        'drawer': 'var(--drawer-shadow-offset) rgba(var(--color-shadow), var(--drawer-shadow-opacity))',
      },
      transitionTimingFunction: {
        'timing-scale-100': 'var(--timing-scale-100)',
        'timing-scale-200': 'var(--timing-scale-200)',
        'timing-scale-300': 'var(--timing-scale-300)',
        'timing-scale-400': 'var(--timing-scale-400)',
        'timing-scale-500': 'var(--timing-scale-500)',
        'timing-scale-600': 'var(--timing-scale-600)',
      },
      zIndex: {
        'header': 'var(--z-layers-header)',
        'modal': 'var(--z-layers-modal)',
        'voiceflow': 'var(--z-layers-voiceflow)',
      },
    },
  },
  plugins: [],
}
